            - name: GitHub Issues to Azure DevOps
  # You may pin to the exact commit or the version.
  # uses: danhellem/github-actions-issue-to-work-item@e077ff031c704672afb932c8718370df12b90f08
  uses: danhellem/github-actions-issue-to-work-item@v2.3
          
